# Change these first
owner: AI4EOSC # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: AI4EOSC
    url: https://ai4eosc.eu
    icon: https://raw.githubusercontent.com/ai4eosc/status/master/static/logo.png

  # Dashboards
  - name: AI4EOSC dev training dashboard
    url: https://dashboard.dev.ai4eosc.eu
    icon: https://raw.githubusercontent.com/ai4eosc/status/master/static/logo.png
  - name: iMagine dev training dashboard
    url: https://dashboard.dev.imagine-ai.eu
    icon: https://raw.githubusercontent.com/ai4eosc/status/master/static/logo-imagine.png
    
  # PAPI
  - name: AI4EOSC Platform API
    url: https://api.dev.ai4eosc.eu
    icon: https://raw.githubusercontent.com/ai4eosc/status/master/static/logo.png

  # Cookiecutter
  - name: AI4EOSC repository template generator
    url: https://templates.cloud.ai4eosc.eu/
    icon: https://raw.githubusercontent.com/ai4eosc/status/master/static/logo.png

  # Cloud endpoints
  - name: Provider IFCA-LCG2   org.openstack.nova
    url: https://api.cloud.ifca.es:5000/v3
    icon: https://raw.githubusercontent.com/ai4eosc/status/master/static/logo-ifca.png

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /status
  logoUrl: https://raw.githubusercontent.com/ai4eosc/status/master/static/logo.png
  theme: light
  name: AI4EOSC service and platform status
  introTitle: "AI platform for the European Open Science Cloud."
  introMessage: This page provides a real time overview of the [AI4EOSC](https://ai4eosc.eu) platform and services status.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
