# Change these first
owner: AI4EOSC # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Homepage
    url: https://ai4eosc.eu
    icon: https://raw.githubusercontent.com/ai4eosc/status/master/static/logo.png
    assignees:
      - alvarolopez

  # Dashboards
  - name: Dashboard (AI4EOSC)
    url: https://dashboard.cloud.ai4eosc.eu
    icon: https://raw.githubusercontent.com/ai4eosc/status/master/static/logo.png
    assignees:
      - MartaOB

  - name: Dashboard (iMagine)
    url: https://dashboard.cloud.imagine-ai.eu
    icon: https://raw.githubusercontent.com/ai4eosc/status/master/static/logo-imagine.png
    assignees:
      - MartaOB

  - name: Dashboard (AI4Life)
    url: https://dashboard.cloud.ai4eosc.eu
    icon: https://ai4life.eurobioimaging.eu/wp-content/uploads/2022/09/AI4Life-logo_giraffe-nodes-1536x710.png
    assignees:
      - MartaOB

  - name: Dashboard (tutorials)
    url: https://tutorials.cloud.ai4eosc.eu
    icon: https://raw.githubusercontent.com/ai4eosc/status/master/static/logo.png
    assignees:
      - MartaOB

  # LLM APIs
  - name: LLM4EOSC (dev) vLLM API service
    url: https://llm.dev.ai4eosc.eu:8000/v1/models
    icon: https://raw.githubusercontent.com/ai4eosc/status/master/static/logo.png
    asignees: 
      - alvarolopez
    
  - name: LLM4EOSC (dev) Open WebUI API service
    url: https://llm.dev.ai4eosc.eu:5000
    icon: https://raw.githubusercontent.com/ai4eosc/status/master/static/logo.png
    asignees: 
      - alvarolopez
  
  - name: LLM4EOSC (dev) Chatbot service
    url: https://llm.dev.ai4eosc.eu/
    icon: https://raw.githubusercontent.com/ai4eosc/status/master/static/logo.png
    asignees: 
      - alvarolopez

  # Cookiecutter
  - name: Module template generator
    url: https://templates.cloud.ai4eosc.eu/
    icon: https://avatars.githubusercontent.com/u/12502901?v=4
    assignees:
      - vykozlov
      - BorjaEst

  # Storage
  - name: Storage (NextCloud)
    url: https://share.cloud.ai4eosc.eu
    icon: https://avatars.githubusercontent.com/u/19211038?s=280&v=4
    assignees:
      - mariojmdavid

   # MLflow
  - name: MLflow (AI4EOSC)
    url: https://mlflow.cloud.ai4eosc.eu/
    expectedStatusCodes:
      - 200
      - 401
    icon: https://avatars.githubusercontent.com/u/39938107?v=4
    assignees:
      - vykozlov
      - lisanaberberi

  - name: MLflow (iMagine)
    url: https://mlflow.cloud.imagine-ai.eu/
    expectedStatusCodes:
      - 200
      - 401
    icon: https://avatars.githubusercontent.com/u/39938107?v=4
    assignees:
      - vykozlov

  # AI4OS LLM
  - name: AI4OS LLM
    url: https://llm.dev.ai4eosc.eu/
    icon: https://avatars.githubusercontent.com/u/158137808?s=200&v=4
    assignees:
      - alvarolopez

  # Jenkins CI/CD
  - name: CI/CD (Jenkins)
    url: https://jenkins.services.ai4os.eu/
    icon: https://www.jenkins.io/images/jenkins-logo-title-dark.svg
    assignees:
      - alvarolopez
      - vykozlov

  # Provenance
  - name: Provenance
    url: https://provenance.services.ai4os.eu/
    icon: https://raw.githubusercontent.com/ai4eosc/status/master/static/logo.png
    assignees:
      - pedro-predictia

  # MinIO
  - name: MinIO object storage - Provider UPV/GRyCAP
    url: https://minio-inference.cloud.ai4eosc.eu/
    icon: https://raw.githubusercontent.com/ai4eosc/status/master/static/logo-minio.png
    assignees:
      - gmolto

  # OSCAR
  - name: OSCAR - Provider UPV/GRyCAP
    url: https://inference.cloud.ai4eosc.eu
    icon: https://raw.githubusercontent.com/ai4eosc/status/master/static/logo-oscar.jpeg
    assignees:
      - gmolto

  # PAPI
  - name: Platform API
    url: https://api.cloud.ai4eosc.eu
    icon: https://raw.githubusercontent.com/ai4eosc/status/master/static/logo.png
    assignees:
      - IgnacioHeredia

  # Nomad cluster (IFCA endpoint)
  - name: Nomad cluster
    check: "tcp-ping"
    url: 193.146.75.205
    port: 4646
    icon: https://raw.githubusercontent.com/ai4eosc/status/master/static/logo-nomad.png
    assignees:
      - Sftobias

  # Harbor registry
  - name: Docker Registry (Harbor)
    url: https://registry.cloud.ai4eosc.eu
    icon: https://goharbor.io/img/logos/harbor-icon-color.png
    assignees:
      - mariojmdavid
  
  # Helpdesk
  - name: AI4EOSC Helpdesk
    url: https://helpdesk.cloud.ai4eosc.eu/
    icon: https://raw.githubusercontent.com/zammad/zammad/refs/heads/develop/public/favicon.ico
    assignees:
      - vykozlov

  # Cloud endpoints
  - name: Provider IFCA-LCG2 org.openstack.nova
    url: https://api.cloud.ifca.es:5000/v3
    icon: https://raw.githubusercontent.com/ai4eosc/status/master/static/logo-ifca.png
    assignees:
      - aidaph

  - name: Provider NCG-INGRID-PT (INCD) org.openstack.nova
    url: https://stratus.ncg.ingrid.pt:5000/v3
    icon: https://raw.githubusercontent.com/ai4eosc/status/master/static/logo-incd.png
    assignees:
      - mariojmdavid

  - name: Provider IISAS-FedCloud org.openstack.nova
    url: https://cloud.ui.savba.sk:5000/v3
    icon: https://raw.githubusercontent.com/ai4eosc/status/master/static/logo-iisas.jpeg
    assignees:
      - tdviet

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.ai4eosc.eu
  # baseUrl: /status
  logoUrl: https://raw.githubusercontent.com/ai4eosc/status/master/static/logo.png
  theme: light
  name: AI4EOSC service and platform status
  introTitle: "AI platform for the European Open Science Cloud."
  introMessage: This page provides a real time overview of the [AI4EOSC](https://ai4eosc.eu) platform and services status.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
